source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

# api tols
gem "rails", "~> 7.0.4", ">= 7.0.4.2"
gem "puma", "~> 5.0"
gem "bootsnap", require: false

# database 
gem "pg", "~> 1.1"

# rest client 
gem "rack-cors"
gem 'active_model_serializers', '~> 0.10.0'

# translation
gem 'i18n'

# authentication and users
gem 'devise_token_auth'
gem 'devise'

# image processing
gem 'gravatar_image_tag'
gem 'mini_magick'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 3.6'
  gem 'database_cleaner'
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'shoulda-matchers', require: false
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'rubocop-rails'
end

group :development do
end

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
